Fix for strange AVRO exception "java.lang.NoClassDefFoundError: Could not initialize class org.apache.avro.generic.GenericData" which had to do with maven dependencies being confused with duplicate dependency chains in twitter-demo.  Twitter demo now only depends on tile-service which will pull in all the correct dependencies (tile-generation, binning utilities and scala-library).  This was preventing us from deploying the revised twitter demo to the demo site.